  CREATE TABLE "PRUEBA"."HCB_INVERSION" 
   (	"MONTO_INVERSION" NUMBER(*,0) NOT NULL ENABLE, 
	"TASA_INTERES_ANUAL" FLOAT(126) NOT NULL ENABLE, 
	"PLAZO_MESES" NUMBER NOT NULL ENABLE, 
	"CANT_CUPONES_ANUAL" NUMBER NOT NULL ENABLE, 
	"ID_INVERSION" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "HCB_INVERSION_PK" PRIMARY KEY ("ID_INVERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "PRUEBA"."HCB_INVERSION"."MONTO_INVERSION" IS 'Monto de la inversion';
   COMMENT ON COLUMN "PRUEBA"."HCB_INVERSION"."TASA_INTERES_ANUAL" IS 'Tasa de Interes anual';
   COMMENT ON COLUMN "PRUEBA"."HCB_INVERSION"."PLAZO_MESES" IS 'Plazo en meses';
   COMMENT ON COLUMN "PRUEBA"."HCB_INVERSION"."CANT_CUPONES_ANUAL" IS 'Cantidad de cupones por año';
   COMMENT ON COLUMN "PRUEBA"."HCB_INVERSION"."ID_INVERSION" IS 'Id';

  CREATE OR REPLACE TRIGGER "PRUEBA"."HCB_INVERSION" 
BEFORE INSERT ON HCB_INVERSION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_INVERSION IS NULL THEN
      SELECT HCB_INVERSIONES_SEC.NEXTVAL INTO :NEW.ID_INVERSION FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRUEBA"."HCB_INVERSION" ENABLE;




  CREATE TABLE "PRUEBA"."HCB_INVERSION_DETALLE" 
   (	"ID_DETALLE" NUMBER NOT NULL ENABLE, 
	"CUPON" NUMBER NOT NULL ENABLE, 
	"SALDO_INVERSION" NUMBER NOT NULL ENABLE, 
	"INTERESS_GANADOS" NUMBER(*,0) NOT NULL ENABLE, 
	"SALDO_CAPITALIZADO" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_INVERSION" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "HCB_INVERSION_DETALLE_PK" PRIMARY KEY ("ID_DETALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE TRIGGER "PRUEBA"."HCB_TR_INVERSION_DETALLE" 
BEFORE INSERT ON HCB_INVERSION_DETALLE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_DETALLE IS NULL THEN
      SELECT HCB_INVERSION_DETALLE_SQ.NEXTVAL INTO :NEW.ID_INVERSION FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRUEBA"."HCB_TR_INVERSION_DETALLE" ENABLE;




  CREATE TABLE "PRUEBA"."HCB_INVERSION_ENCABEZADO" 
   (	"TOTAL_INTERES" NUMBER NOT NULL ENABLE, 
	"SALDO_CAPITALIZDO_FINAL" NUMBER NOT NULL ENABLE, 
	"ID_ENCABEZADO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ID_INVERSION" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "INVERSION_ENCABEZADO_PK" PRIMARY KEY ("ID_ENCABEZADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE TRIGGER "PRUEBA"."HCB_TR_INVERSION_ENCABEZADO" 
BEFORE INSERT ON HCB_INVERSION_ENCABEZADO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_ENCABEZADO IS NULL THEN
      SELECT HCB_INVERSION_ENCABEZADO_SQ.NEXTVAL INTO :NEW.ID_ENCABEZADO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRUEBA"."HCB_TR_INVERSION_ENCABEZADO" ENABLE;
